// keyBenefitsHighlighted is derived deterministically from the tags on the
// chunks actually retrieved for this answer — not generated by the LLM — so
// it can never list a benefit the answer wasn't actually grounded in.

const BENEFIT_LABELS = {
  'benefit:proof_based_collections': 'Proof-based UPI collections with instant reconciliation',
  'benefit:zero_gateway_commission': 'Zero payment gateway commission on maintenance collections',
  'benefit:flexible_expense_splitting': 'Flexible expense-splitting rules per society bylaws',
  'benefit:instant_pwa_install': 'Instant PWA install — no app store needed',
  'benefit:transparent_ledger': 'Transparent per-flat Dr/Cr ledger',
  'benefit:corpus_fund_management': 'Dedicated corpus fund tracking',
  'benefit:lower_total_cost': 'Lower total cost vs. gateway-commission platforms',
  'benefit:fast_migration': 'Fast, low-friction migration from spreadsheets',
  'benefit:dedicated_support': 'Dedicated onboarding support'
};

/**
 * @param {Array<{ chunk: { tags: string[] } }>} rankedChunks
 * @param {number} [cap]
 * @returns {string[]}
 */
function extractKeyBenefits(rankedChunks, cap = 4) {
  const seen = new Set();
  const labels = [];

  for (const { chunk } of rankedChunks) {
    for (const tag of chunk.tags || []) {
      if (!tag.startsWith('benefit:')) continue;
      const label = BENEFIT_LABELS[tag];
      if (label && !seen.has(tag)) {
        seen.add(tag);
        labels.push(label);
      }
      if (labels.length >= cap) return labels;
    }
  }

  return labels;
}

module.exports = { extractKeyBenefits, BENEFIT_LABELS };
